# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'test.xcworkspace'

abstract_target 'test' do
    pod 'AFNetworking', '~> 3.0', :subspecs => ['UIKit'], :inhibit_warnings => false
    pod 'KVOController'
    pod 'Masonry'

    pod 'SDWebImage'

    target 'test' do
      project 'test.xcodeproj'

    end
    
end

